export enum EVENT {
	KEYDOWN = "keydown",
	KEYUP = "keyup",
	MOUSE_MOVE = "mousemove",
	RESIZE = "resize",
	FOCUS = "focus",
	DRAG_OVER = "dragover",
	GESTURE_END = "gestureend",
	GESTURE_START = "gesturestart",
	GESTURE_CHANGE = "gesturechange",
	POINTER_MOVE = "pointermove",
	POINTER_DOWN = "pointerdown",
	POINTER_UP = "pointerup",
	POINTER_CANCEL = "pointercancel",
	WHEEL = "wheel",
	TOUCH_START = "touchstart",
	TOUCH_END = "touchend",
	TOUCH_MOVE = "touchmove",
	TOUCH_CANCEL = "touchcancel",
	DOUBLE_CLICK = "dblclick",
}
