export enum EventType {
	DOUBLE_CLICK = "dblclick",
	DRAG_OVER = "dragover",
	FOCUS = "focus",
	GESTURE_END = "gestureend",
	GESTURE_CHANGE = "gesturechange",
	GESTURE_START = "gesturestart",
	KEY_DOWN = "keydown",
	KEY_UP = "keyup",
	MOUSE_MOVE = "mousemove",
	POINTER_CANCEL = "pointercancel",
	POINTER_DOWN = "pointerdown",
	POINTER_MOVE = "pointermove",
	POINTER_UP = "pointerup",
	RESIZE = "resize",
	TOUCH_CANCEL = "touchcancel",
	TOUCH_END = "touchend",
	TOUCH_MOVE = "touchmove",
	TOUCH_START = "touchstart",
	WHEEL = "wheel",
}
